In [45]:
import pandas as pd

In [46]:
df= pd.read_csv("IMDB Dataset.csv")

In [47]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [48]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [49]:
df.drop_duplicates(inplace= True)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49582 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     49582 non-null  object
 1   sentiment  49582 non-null  object
dtypes: object(2)
memory usage: 1.1+ MB

In [51]:
df ["review"]= df["review"].str.lower()

In [52]:
import re

In [53]:
def remove_url(text):
    text = re.sub(r"http\S+", "", text)
    return text


df["review"] = df["review"].apply(remove_url)

In [54]:
def remove_punctuations(text):
    text = re.sub(r"[^A-Za-z0-9\s]", "",text)
    return text

df["review"] = df["review"].apply(remove_punctuations)

In [55]:
def remove_html(text):
    text= re.sub(r"<.*?>", "", text)
    return text

df["review"] = df["review"].apply(remove_html)

In [56]:
import nltk
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\arpan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\arpan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\arpan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [57]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords


def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text = text.replace(word, "")

    return text

df["review"] = df["review"].apply(remove_stopwords)

In [58]:
df.head()

                                              review sentiment
0  e    revewers  nted   wtchg  1 oz epode ll  ho...  positive
1   wderful ltle producti br br  filming techniqu...  positive
2   thought ths   wderful wy  spend tme   o hot s...  positive
3  bsclly res  fmly   lttle boy jke thks res  zom...  negative
4  petter mtte love   time  mey   vully stunng fi...  positive

In [59]:
from nltk.stem import PorterStemmer

def stemming(text):
    tokens = word_tokenize(text)
    ps = PorterStemmer()
    stemmed = []

    for token in tokens:
        stemmed_tokens = ps.stem(token)
        stemmed.append(stemmed_tokens)

    return " ".join(stemmed)

df["review"] = df["review"].apply(stemming)

In [60]:
df.head()

                                              review sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...  positive
1  wder ltle producti br br film techniqu unssum ...  positive
2  thought th wder wy spend tme o hot summer week...  positive
3  bsclli re fmli lttle boy jke thk re zomb close...  negative
4  petter mtte love time mey vulli stunng film wt...  positive

In [63]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["sentiment"]=le.fit_transform(df["sentiment"])

In [64]:
df.head()

                                              review  sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...          1
1  wder ltle producti br br film techniqu unssum ...          1
2  thought th wder wy spend tme o hot summer week...          1
3  bsclli re fmli lttle boy jke thk re zomb close...          0
4  petter mtte love time mey vulli stunng film wt...          1